### ISSUE TITLE
[BUG]: ValueError: Langchain is too old

### ISSUE THREAD

**Issue by SimonB97** [Chainlit/chainlit#104]
I have langchain 0.0.215 installed but am getting this error:

```
PS C:\Users\sbene\Projects\CodeGPT> & C:/Users/sbene/miniconda3/envs/docschat/python.exe c:/Users/sbene/Projects/CodeGPT/src/chainlit_app.py
2023-06-25 22:29:23 - Created default config file at C:\Users\sbene\Projects\CodeGPT\.chainlit\config.toml
Traceback (most recent call last):
  File "c:\Users\sbene\Projects\CodeGPT\src\chainlit_app.py", line 3, in <module>
    import chainlit as cl
  File "C:\Users\sbene\miniconda3\envs\docschat\lib\site-packages\chainlit\__init__.py", line 20, in <module>
    from chainlit.cache import cache
  File "C:\Users\sbene\miniconda3\envs\docschat\lib\site-packages\chainlit\cache.py", line 6, in <module>
    from chainlit.lc import LANGCHAIN_INSTALLED
  File "C:\Users\sbene\miniconda3\envs\docschat\lib\site-packages\chainlit\lc\__init__.py", line 5, in <module>
    raise ValueError(
ValueError: LangChain version is too old, expected >= 0.0.198. Run `pip install langchain --upgrade`
```

**Comment by SimonB97** [comment]
Nevermind, i installed chainlit in an existing environment with langchain pre-installed and it seems to have mixed up something.. creating a new environment solved the issue.
