### ISSUE TITLE
Getting the DLopen issue

### ISSUE THREAD

**Issue by adithyaboyapati** [Chainlit/chainlit#109]
I was getting the below error when executing chainlit hello command in mac OS 13.4.1

Traceback (most recent call last):
  File "/Users/user/PycharmProjects/Chainlit-Zomato-GPT/env/bin/chainlit", line 5, in <module>
    from chainlit.cli import cli
  File "/Users/user/PycharmProjects/Chainlit-Zomato-GPT/env/lib/python3.9/site-packages/chainlit/__init__.py", line 9, in <module>
    from chainlit.telemetry import trace
  File "/Users/user/PycharmProjects/Chainlit-Zomato-GPT/env/lib/python3.9/site-packages/chainlit/telemetry.py", line 1, in <module>
    import uptrace
  File "/Users/user/PycharmProjects/Chainlit-Zomato-GPT/env/lib/python3.9/site-packages/uptrace/__init__.py", line 4, in <module>
    from .uptrace import (
  File "/Users/user/PycharmProjects/Chainlit-Zomato-GPT/env/lib/python3.9/site-packages/uptrace/uptrace.py", line 11, in <module>
    from .logs import configure_logs
  File "/Users/user/PycharmProjects/Chainlit-Zomato-GPT/env/lib/python3.9/site-packages/uptrace/logs.py", line 3, in <module>
    import grpc
  File "/Users/user/PycharmProjects/Chainlit-Zomato-GPT/env/lib/python3.9/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/user/PycharmProjects/Chainlit-Zomato-GPT/env/lib/python3.9/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/adithyaboyapati/PycharmProjects/Chainlit-Zomato-GPT/env/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

**Comment by willydouhard** [comment]
It looks like https://github.com/Chainlit/chainlit/issues/56
