### ISSUE TITLE
cl.Avatar stopped working in 1.1.304

### ISSUE THREAD

**Issue by nagarjunr** [Chainlit/chainlit#1093]
**Describe the bug**
cl.Avatar gives the following error with the latest version of chainlit. I am using the version [1.1.304](https://github.com/Chainlit/chainlit/releases/tag/1.1.304)

**Screenshots**
2024-06-21 15:28:31 - 'Avatar'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/chainlit/utils.py", line 44, in wrapper
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/src/main.py", line 57, in start_chat
    await cl.Avatar(
          ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/chainlit/utils.py", line 70, in __getattr__
    module_path = registry[name]

**Additional context**
Tried to run locally as well as docker, both has the same behaviour.

**Comment by nagarjunr** [comment]
Issue was due to the braking change in 1.1.300. Fixed based on the recommendation in 1.1.300 release.

**Comment by inrsta** [comment]
Do you happen to have a solution about having an Avatar for the user?
