### ISSUE TITLE
Infinite delay during google oauth 

### ISSUE THREAD

**Issue by yashkumarverma-fampay** [Chainlit/chainlit#1120]
**Describe the bug**
- When user selects a google account, the page remains stuck on google's page, and ultimately breaks with a log line saying `some unexpected error occured`. 

**To Reproduce**
- deploy chainlit application on kubernetes 

**Expected behavior**
- redirect should work as expected, and UI should proceed to further flows.

**Screenshots**

**Desktop (please complete the following information):**
Google Chrome | 126.0.6478.127 (Official Build) (arm64)

**Additional context**
Logs
```
INFO:     172.31.171.51:39494 - "GET / HTTP/1.1" 200 OK
INFO:     172.31.171.51:39508 - "GET / HTTP/1.1" 200 OK
2024-07-05 12:34:33 - HTTP Request: POST https://oauth2.googleapis.com/token "HTTP/1.1 400 Bad Request"
INFO:     172.31.163.68:44864 - "GET /auth/oauth/google/callback?state=n%3F27IVE7%2F%24T1A5GssRC%3ETYy7kSwr4NeB&code=4%2F0ATx3LY73LUykj1Z20szKMVB4aPlMjak3PGtbZWtE-ZnihP5a8wye4pCWUUpYFs0jVuZjNQ&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&hd=yashkumarverma.in&prompt=none HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/engineio/async_drivers/asgi.py", line 74, in __call__
    await self.other_asgi_app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/chainlit/server.py", line 510, in oauth_callback
    token = await provider.get_token(code, url)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/chainlit/oauth_providers.py", line 113, in get_token
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://oauth2.googleapis.com/token'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
INFO:     172.31.163.68:44866 - "GET /favicon.ico HTTP/1.1" 200 OK
2024-07-05 12:34:33 - An unexpected error occurred:
INFO:     172.31.171.51:54366 - "GET / HTTP/1.1" 200 OK
INFO:     172.31.171.51:54368 - "GET / HTTP/1.1" 200 OK
```

**Comment by sahabcomplya** [comment]
Getting the same
