### ISSUE TITLE
Upgrade to latest literalai-sdk

### ISSUE THREAD

**Issue by dokterbob** [Chainlit/chainlit#1314]
Requires extensive automated and manual testing and code changes (imports) which are part of https://github.com/Chainlit/chainlit/pull/1267.

**Comment by bleonard** [comment]
This would be good. I don't know if it's fixed in the current literalai, but I am getting a crash when `cl.instrument_openai()` and sending tool response. If it matters, I am streaming and using llama_index.

```
2024-11-21 16:20:39 - Exception in callback Dispatcher.span.<locals>.wrapper.<locals>.handle_future_result(span_id='Workflow.run...-608d7833c1cc', bound_args=<BoundArgumen...kwargs={})]})>, instance=<app.agents.t...t 0x15c197d60>, context=<_contextvars...t 0x15c20f9c0>)(<WorkflowHand...9/v/dict_type>) at /test-agent-workflow/.venv/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py:273
handle: <Handle Dispatcher.span.<locals>.wrapper.<locals>.handle_future_result(span_id='Workflow.run...-608d7833c1cc', bound_args=<BoundArgumen...kwargs={})]})>, instance=<app.agents.t...t 0x15c197d60>, context=<_contextvars...t 0x15c20f9c0>)(<WorkflowHand...9/v/dict_type>) at /test-agent-workflow/.venv/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py:273>
Traceback (most recent call last):
  File "/.pyenv/versions/3.10.15/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/test-agent-workflow/.venv/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 283, in handle_future_result
    raise exception
  File "/test-agent-workflow/.venv/lib/python3.10/site-packages/llama_index/core/workflow/workflow.py", line 379, in _run_workflow
    raise exception_raised
  File "/test-agent-workflow/.venv/lib/python3.10/site-packages/llama_index/core/workflow/workflow.py", line 234, in _task
    raise e from None
  File "/test-agent-workflow/.venv/lib/python3.10/site-packages/llama_index/core/workflow/workflow.py", line 230, in _task
    new_ev = await instrumented_step(**kwargs)
  File "/test-agent-workflow/.venv/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 357, in async_wrapper
    result = await func(*args, **kwargs)
  File "/test-agent-workflow/app/agents/tool_router.py", line 33, in handle_llm_input
    return await llm_tool_input(ctx, self.history, self.llm, self.tools)
  File "/test-agent-workflow/app/steps/llm_tool_input.py", line 48, in llm_tool_input
    async for response in chat_response_gen:
  File "/test-agent-workflow/.venv/lib/python3.10/site-packages/llama_index/core/llms/callbacks.py", line 88, in wrapped_gen
    async for x in f_return_val:
  File "/test-agent-workflow/.venv/lib/python3.10/site-packages/llama_index/llms/openai/base.py", line 712, in gen
    async for response in await aclient.chat.completions.create(
  File "/test-agent-workflow/.venv/lib/python3.10/site-packages/literalai/wrappers.py", line 82, in wrapped
    await before_func(context, *args, **kwargs)
  File "/test-agent-workflow/.venv/lib/python3.10/site-packages/literalai/instrumentation/openai.py", line 205, in before
    generation = init_generation(metadata["type"], kwargs)
  File "/test-agent-workflow/.venv/lib/python3.10/site-packages/literalai/instrumentation/openai.py", line 123, in init_generation
    return ChatGeneration(
  File "/test-agent-workflow/.venv/lib/python3.10/site-packages/pydantic/_internal/_dataclasses.py", line 141, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ChatGeneration
messages.2.tool_calls.0
  Input should be a valid dictionary [type=dict_type, input_value='ChoiceDeltaToolCall(inde...\'), type=\'function\')', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/dict_type

```
