### ISSUE TITLE
TypeError: bases must be types

### ISSUE THREAD

**Issue by tiero** [Chainlit/chainlit#133]
Hello! I tried [this example in the docs](https://docs.chainlit.io/integrations/langchain) using langchain and Sync approach with OpenAI but I get the following error when running it:

```sh
chainlit run app.py -w
Traceback (most recent call last):
  File "/opt/homebrew/bin/chainlit", line 5, in <module>
    from chainlit.cli import cli
  File "/opt/homebrew/lib/python3.10/site-packages/chainlit/__init__.py", line 9, in <module>
    from chainlit.lc import (
  File "/opt/homebrew/lib/python3.10/site-packages/chainlit/lc/__init__.py", line 13, in <module>
    from chainlit.telemetry import trace
  File "/opt/homebrew/lib/python3.10/site-packages/chainlit/telemetry.py", line 1, in <module>
    import uptrace
  File "/opt/homebrew/lib/python3.10/site-packages/uptrace/__init__.py", line 4, in <module>
    from .uptrace import (
  File "/opt/homebrew/lib/python3.10/site-packages/uptrace/uptrace.py", line 11, in <module>
    from .logs import configure_logs
  File "/opt/homebrew/lib/python3.10/site-packages/uptrace/logs.py", line 5, in <module>
    from opentelemetry.exporter.otlp.proto.grpc._log_exporter import (
  File "/opt/homebrew/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/grpc/_log_exporter/__init__.py", line 19, in <module>
    from opentelemetry.exporter.otlp.proto.common._log_encoder import encode_logs
  File "/opt/homebrew/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/common/_log_encoder.py", line 16, in <module>
    from opentelemetry.exporter.otlp.proto.common._internal._log_encoder import (
  File "/opt/homebrew/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 21, in <module>
    from opentelemetry.proto.common.v1.common_pb2 import (
  File "/opt/homebrew/lib/python3.10/site-packages/opentelemetry/proto/common/v1/common_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/opt/homebrew/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 40, in <module>
    from google.protobuf.internal import api_implementation
  File "/opt/homebrew/lib/python3.10/site-packages/google/protobuf/internal/api_implementation.py", line 104, in <module>
    from google.protobuf.pyext import _message
TypeError: bases must be types
```

**Comment by willydouhard** [comment]
I found [this issue](https://github.com/spesmilo/electrum/issues/7825) that looks similar. Can you try to manually reinstall protobuf as discussed?

**Comment by tiero** [comment]
protobuf was not installed in the first place. Not sure if it's documented as a required dependency in other places, but would be helpful to have it in the tutorial as well
