### ISSUE TITLE
LookupError in ChainlitContext: ContextVar 'local_steps' Not Found When Converting FastAPI to WSGI with a2wsgi

### ISSUE THREAD

**Issue by seleniumpython2016** [Chainlit/chainlit#1494]
I use fastapi mount chainlit，and I use a2wsgi conver to wsgi，beacase I use gunicorn。the chanlit version is 1.3.0rc1 .when I open the chainlit url，the page can open，but the page shows that " it can not connect the server ". the errror log as the follows, who can help me?

2024-10-31 17:38:59 - <ContextVar name='local_steps' at 0x7fde381385e0>
Traceback (most recent call last):
File "/opt/app/.venv/lib/python3.10/site-packages/chainlit/utils.py", line 44, in wrapper
return await user_function(**params_values)
File "/opt/app/.venv/lib/python3.10/site-packages/chainlit/step.py", line 99, in async_wrapper
async with Step(
File "/opt/app/.venv/lib/python3.10/site-packages/chainlit/step.py", line 431, in aenter
previous_steps = local_steps.get() or []
LookupError: <ContextVar name='local_steps' at 0x7fde381385e0>
2024-10-31 17:39:44 - Translated markdown file for zh-CN not found. Defaulting to chainlit.md.
2024-10-31 17:39:45 - <ContextVar name='local_steps' at 0x7fde381385e0>

**Comment by seleniumpython2016** [comment]
Thank you for your reply. The app. py code is as follows：
        from fastapi import FastAPI
        from chainlit.utils import mount_chainlit
        from a2wsgi import ASGIMiddleware
        application = FastAPI()
        @application.get("/app")
        def read_main():
            return {"message": "Hello World from main app"}
        mount_chainlit(app=application, target="my_cl_app.py", path="/chainlit")
        application = ASGIMiddleware(application)
the my_cl_app.py code as follows:
          import chainlit as cl
          from generate.case_generate import CaseGenerate
          @cl.on_chat_start
          async def on_chat_start():
              msg = cl.Message(content=f"I will help you!")
              await msg.send()
          
          @cl.on_message
          async def on_message(message: cl.Message):
              files = message.elements
              print(files)
              if files is None or len(files) ==0:
                  await cl.Message(content="please upload the file!").send()
              files_path = []
              for file in files:
                  files_path.append(file.path)
              chain = CaseGenerate.case_gen(files_path,message.content)
              human_input = "auto case format"
              stream = await chain.arun(
                  {"human_input":human_input},
              )
              await cl.Message(content=stream).send()

I use  gunicorn  run the fastapi( a2wsgi conver to wsgi) ，looking forward to your reply！

**Comment by dokterbob** [comment]
@dosu Any idea what's going on?

**Comment by dokterbob** [comment]
@dosu Could you please suggest a clearer title for the issue?

**Comment by seleniumpython2016** [comment]
@dosu  Can you provide specific instructions on how to use it based on the code I provided above?

**Comment by gregmeldrum** [comment]
@dosu Is there any way to initialize `local_steps` from my application code? I don't want to change `init_ws_context` or `init_http_context`.

**Comment by danielkanzel** [comment]
I have same problem too
