### ISSUE TITLE
Unable to import chainlit

### ISSUE THREAD

**Issue by kenual** [Chainlit/chainlit#1619]
**Describe the bug**
Unable to import chainlit due to Pydantic error

**To Reproduce**
On MacOS Python 3.9.6

1. pip install chainlit
2. start python console
3. at >> type import chainlit
4. See error with error stack below

**Expected behavior**
import chainlit succeeds

**Error stack **

Python 3.9.6 (default, Nov 11 2024, 03:15:38) 
[Clang 16.0.0 (clang-1600.0.26.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import chainlit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ken/Documents/GitHub/chainlit-test/.venv/lib/python3.9/site-packages/chainlit/__init__.py", line 18, in <module>
    from chainlit.action import Action
  File "/Users/ken/Documents/GitHub/chainlit-test/.venv/lib/python3.9/site-packages/chainlit/action.py", line 5, in <module>
    from chainlit.telemetry import trace_event
  File "/Users/ken/Documents/GitHub/chainlit-test/.venv/lib/python3.9/site-packages/chainlit/telemetry.py", line 12, in <module>
    from chainlit.config import config
  File "/Users/ken/Documents/GitHub/chainlit-test/.venv/lib/python3.9/site-packages/chainlit/config.py", line 538, in <module>
    config = load_config()
  File "/Users/ken/Documents/GitHub/chainlit-test/.venv/lib/python3.9/site-packages/chainlit/config.py", line 507, in load_config
    settings = load_settings()
  File "/Users/ken/Documents/GitHub/chainlit-test/.venv/lib/python3.9/site-packages/chainlit/config.py", line 479, in load_settings
    code_settings = CodeSettings(action_callbacks={})
  File "/Users/ken/Documents/GitHub/chainlit-test/.venv/lib/python3.9/site-packages/pydantic/_internal/_dataclasses.py", line 121, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
  File "/Users/ken/Documents/GitHub/chainlit-test/.venv/lib/python3.9/site-packages/pydantic/_internal/_mock_val_ser.py", line 100, in __getattr__
    raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: `CodeSettings` is not fully defined; you should define `Action`, then call `pydantic.dataclasses.rebuild_dataclass(CodeSettings)`.

For further information visit https://errors.pydantic.dev/2.10/u/class-not-fully-defined
>>>

**Comment by willydouhard** [comment]
Should be fixed with the latest release!

**Comment by kenual** [comment]
The issue is fixed in chainlit==2.0.0 . Thank you!
