### ISSUE TITLE
Failed to deploy in AWS Ec2 instance

### ISSUE THREAD

**Issue by anyoneai** [Chainlit/chainlit#251]
Hi! I'm trying to get a dockerized version of a Chainlit app running in an Ec2 instance. I didn't find any tutorial about AWS so started on my own.

I have set `public = false` and the corresponding `id` in the `config.toml` file. I also configured AWS Cloudfront and Route53 to get the domain name using HTTPS but when I try to access the UI it loads the chat interface but saying **You are not part of this project.**, even while I'm logged in.

In the app logs I see the following output:

```console
backend_1  | 2023-08-02 19:10:46 - Your app is available at http://localhost:8000
backend_1  | The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
backend_1  | 2023-08-02 19:13:43 - The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
backend_1  | ERROR:    Exception in ASGI application
backend_1  | Traceback (most recent call last):
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
backend_1  |     result = await app(  # type: ignore[func-returns-value]
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend_1  |     return await self.app(scope, receive, send)
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/fastapi/applications.py", line 282, in __call__
backend_1  |     await super().__call__(scope, receive, send)
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
backend_1  |     await self.middleware_stack(scope, receive, send)
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend_1  |     raise exc
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend_1  |     await self.app(scope, receive, _send)
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
backend_1  |     await self.app(scope, receive, send)
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend_1  |     raise exc
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend_1  |     await self.app(scope, receive, sender)
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
backend_1  |     raise e
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
backend_1  |     await self.app(scope, receive, send)
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
backend_1  |     await route.handle(scope, receive, send)
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
backend_1  |     await self.app(scope, receive, send)
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
backend_1  |     response = await func(request)
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/fastapi/routing.py", line 241, in app
backend_1  |     raw_response = await run_endpoint_function(
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
backend_1  |     return await dependant.call(**values)
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/chainlit/server.py", line 261, in get_member_role
backend_1  |     auth_client = await get_auth_client_from_request(request)
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/chainlit/client/utils.py", line 61, in get_auth_client_from_request
backend_1  |     auth_client = await get_auth_client(authorization)
backend_1  |   File "/home/app/.local/lib/python3.10/site-packages/chainlit/client/utils.py", line 15, in get_auth_client
backend_1  |     raise ConnectionRefusedError("No access token provided")
backend_1  | ConnectionRefusedError: No access token provided
```

What is happening? Am I doing the right steps to deploy this?

**Comment by willydouhard** [comment]
Did you authorize your custom domain name in your chainlit cloud project?
