### ISSUE TITLE
Llama Index Integration Broken?

### ISSUE THREAD

**Issue by ibicdev** [Chainlit/chainlit#256]
The llama-index integration example from Chainlit doc (https://docs.chainlit.io/integrations/llama-index) throws `LookupError: <ContextVar name='emitter' at 0x7f180cba02c0>` - pretty sure it was working a few weeks ago.

The source code is exactly the same as the example.  Full error message:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/ibicdev/anaconda3/lib/python3.9/site-packages/chainlit/context.py", line 20, in get_emitter
    return emitter_var.get()
LookupError: <ContextVar name='emitter' at 0x7f180cba02c0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ibicdev/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/ibicdev/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ibicdev/anaconda3/lib/python3.9/site-packages/llama_index/llms/base.py", line 133, in wrapped_llm_chat
    event_id = callback_manager.on_event_start(
  File "/home/ibicdev/anaconda3/lib/python3.9/site-packages/llama_index/callbacks/base.py", line 80, in on_event_start
    handler.on_event_start(event_type, payload, event_id=event_id, **kwargs)
  File "/home/ibicdev/anaconda3/lib/python3.9/site-packages/chainlit/llama_index/callbacks.py", line 44, in on_event_start
    Message(
  File "/home/ibicdev/anaconda3/lib/python3.9/site-packages/chainlit/message.py", line 176, in __init__
    super().__post_init__()
  File "/home/ibicdev/anaconda3/lib/python3.9/site-packages/chainlit/message.py", line 33, in __post_init__
    self.emitter = get_emitter()
  File "/home/ibicdev/anaconda3/lib/python3.9/site-packages/chainlit/context.py", line 22, in get_emitter
    raise ChainlitContextException()
chainlit.context.ChainlitContextException: Chainlit context not found
```

**Comment by SiddhantSadangi** [comment]
I get a different error

```
2023-08-06 14:24:49 - 'Response' object has no attribute 'response_gen'
Traceback (most recent call last):
  File "C:\Users\siddh\miniconda3\envs\py38\lib\site-packages\chainlit\utils.py", line 36, in wrapper
    return await user_function(**params_values)
  File ".\llama_index.py", line 61, in main
    for token in response.response_gen:
AttributeError: 'Response' object has no attribute 'response_gen'
```

**Comment by willydouhard** [comment]
I just copy pasted the integration code and it's working on my machine.

The `Chainlit context not found` means that a `Message` was instantiated outside of the chainlit context (meaning outside of `on_chat_start` or `on_message`)

**Comment by SiddhantSadangi** [comment]
@willydouhard 
It's not working for me as well

```
❯ chainlit run .\llama_index.py -w
2023-08-06 16:10:11 - Created default config file at C:\Users\siddh\OneDrive\Desktop\Code\chainlit\apps\llama_index\.chainlit\config.toml
2023-08-06 16:10:15 - Loading all indices.
2023-08-06 16:10:15 - Your app is available at http://localhost:8000
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\siddh\miniconda3\envs\py38\lib\site-packages\chainlit\context.py", line 20, in get_emitter
    return emitter_var.get()
LookupError: <ContextVar name='emitter' at 0x0000016F83D4F4A0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\siddh\miniconda3\envs\py38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\siddh\miniconda3\envs\py38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\siddh\miniconda3\envs\py38\lib\site-packages\llama_index\llms\base.py", line 133, in wrapped_llm_chat
    event_id = callback_manager.on_event_start(
  File "C:\Users\siddh\miniconda3\envs\py38\lib\site-packages\llama_index\callbacks\base.py", line 80, in on_event_start
    handler.on_event_start(event_type, payload, event_id=event_id, **kwargs)
  File "C:\Users\siddh\miniconda3\envs\py38\lib\site-packages\chainlit\llama_index\callbacks.py", line 45, in on_event_start
    Message(
  File "C:\Users\siddh\miniconda3\envs\py38\lib\site-packages\chainlit\message.py", line 168, in __init__
    super().__post_init__()
  File "C:\Users\siddh\miniconda3\envs\py38\lib\site-packages\chainlit\message.py", line 35, in __post_init__
    self.emitter = get_emitter()
  File "C:\Users\siddh\miniconda3\envs\py38\lib\site-packages\chainlit\context.py", line 22, in get_emitter
    raise ChainlitContextException()
chainlit.context.ChainlitContextException: Chainlit context not found
```

UI is stuck at the LLM step:
![image](https://github.com/Chainlit/chainlit/assets/41324509/221cf947-63f1-4a69-98cd-ce3df98ee56f)

I am using `chainlit==0.6.1`

**Comment by willydouhard** [comment]
Interesting, I can't reproduce. Which version of llama_index are you using? Also can you attach the exact python code you are running (we should be running the same but we never know)

**Comment by ibicdev** [comment]
I was using chainlit 0.5.2 and then updated to 0.6.1 - both with this issue; also tested WSL2 and ubuntu and got the same error.  

Python code
```
import os
import openai

from llama_index.query_engine.retriever_query_engine import RetrieverQueryEngine
from llama_index.callbacks.base import CallbackManager
from llama_index import (
    LLMPredictor,
    ServiceContext,
    StorageContext,
    load_index_from_storage,
)
from langchain.chat_models import ChatOpenAI
import chainlit as cl


openai.api_key = os.environ.get("OPENAI_API_KEY")

try:
    # rebuild storage context
    storage_context = StorageContext.from_defaults(persist_dir="./storage")
    # load index
    index = load_index_from_storage(storage_context)
except:
    from llama_index import GPTVectorStoreIndex, SimpleDirectoryReader

    documents = SimpleDirectoryReader(input_files=["./state_of_the_union.txt"]).load_data()
    index = GPTVectorStoreIndex.from_documents(documents)
    index.storage_context.persist()


@cl.on_chat_start
async def factory():
    llm_predictor = LLMPredictor(
        llm=ChatOpenAI(
            temperature=0,
            model_name="gpt-3.5-turbo",
            streaming=True,
        ),
    )
    service_context = ServiceContext.from_defaults(
        llm_predictor=llm_predictor,
        chunk_size=512,
        callback_manager=CallbackManager([cl.LlamaIndexCallbackHandler()]),
    )

    query_engine = index.as_query_engine(
        service_context=service_context,
        streaming=True,
    )

    cl.user_session.set("query_engine", query_engine)


@cl.on_message
async def main(message):
    query_engine = cl.user_session.get("query_engine")  # type: RetrieverQueryEngine
    response = await cl.make_async(query_engine.query)(message)

    response_message = cl.Message(content="")

    for token in response.response_gen:
        await response_message.stream_token(token=token)

    if response.response_txt:
        response_message.content = response.response_txt

    await response_message.send()

```

**Comment by willydouhard** [comment]
The issue is with the latest llama-index version. If you try with `0.7.19` it should be working. Will investigate what is the breaking change.

**Comment by SiddhantSadangi** [comment]
Works with `llama-index==0.7.17`. Thanks!

**Comment by ibicdev** [comment]
Yes, can confirm it works with `llama-index==0.7.17` for me as well.  Thanks!

**Comment by Skisquaw** [comment]
I'm getting a different issue. I use the above in a clean python 3.9 conda env with /storage deleted and the index is not working properly. Try this:

User
03:50:10 PM
who is Pat Gelsinger?
Chatbot
03:50:10 PM
Based on the given context information, there is no mention of Pat Gelsinger. Therefore, it is not possible to determine who Pat Gelsinger is based on this information alone.

**Comment by ibicdev** [comment]
Couldn't replicate this issue - I got the following answer:

Pat Gelsinger is the CEO of Intel, an American company that helps build computer chips and is planning to make a significant investment in manufacturing in the United States.

**Comment by SiddhantSadangi** [comment]
I was able to replicate it with the same results as @Skisquaw

**Comment by willydouhard** [comment]
Feels like a shortcoming of llama-index. I can reproduce but if I follow up with `is the company Intel mentioned?` Then it finds the right sources that also mention `Pat Gelsinger`.
<img width="1720" alt="Screenshot 2023-08-14 at 17 08 56" src="https://github.com/Chainlit/chainlit/assets/13104895/e6326c32-da25-4aeb-9029-be7b90996c25">

**Comment by ibicdev** [comment]
It might be due to that the sample code tried to load from the default `storage` folder first:
```
storage_context = StorageContext.from_defaults(persist_dir="./storage")
```
In my case this folder already had content from previous documents - after removing it and reran I got expected results.

**Comment by ramnes** [comment]
Just did a bisect of llama_index and the faulty PR is https://github.com/jerryjliu/llama_index/pull/7112

@Skisquaw can you please open another issue for your problem?

**Comment by ramnes** [comment]
@ibicdev @SiddhantSadangi PR #290 with llama_index 0.8.3 should fix this. Can you confirm?

**Comment by ibicdev** [comment]
This is amazing!  I can confirm this PR works with llama-index 0.8.4 (had to learn to build chainlit form source :smiley:).  Thanks for having it fixed so promptly.

**Comment by younes-io** [comment]
I have the issue on https://github.com/Chainlit/chainlit/issues/571
