### ISSUE TITLE
Getting a symbol not found in flat namespace '_CFDataGetBytes' error when run with llama/FAISS/Langchain

### ISSUE THREAD

**Issue by FSDSAbhi** [Chainlit/chainlit#271]
I am running into this error when I am using Chainlit to develop a bot which is based on 

- llama-2-7b-chat.ggmlv3.q8_0
- FAISS
- Langchain
- Python
- HuggingFaceEmbeddings

I am using a MacOS M1 16GB

Traceback (most recent call last):
  File "/Users//Desktop/llama/env/bin/chainlit", line 5, in <module>
    from chainlit.cli import cli
  File "/Users//Desktop/llama/env/lib/python3.10/site-packages/chainlit/__init__.py", line 12, in <module>
    from chainlit.action import Action
  File "/Users//Desktop/llama/env/lib/python3.10/site-packages/chainlit/action.py", line 7, in <module>
    from chainlit.telemetry import trace_event
  File "/Users//Desktop/llama/env/lib/python3.10/site-packages/chainlit/telemetry.py", line 12, in <module>
    import uptrace
  File "/Users//Desktop/llama/env/lib/python3.10/site-packages/uptrace/__init__.py", line 4, in <module>
    from .uptrace import (
  File "/Users/Desktop/llama/env/lib/python3.10/site-packages/uptrace/uptrace.py", line 11, in <module>
    from .logs import configure_logs
  File "/Users//Desktop/llama/env/lib/python3.10/site-packages/uptrace/logs.py", line 3, in <module>
    import grpc
  File "/Users/Desktop/llama/env/lib/python3.10/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users//Desktop/llama/env/lib/python3.10/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/Desktop/llama/env/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_CFDataGetBytes'

**Comment by willydouhard** [comment]
Looks like #56
