### ISSUE TITLE
Display intermediary steps in AsyncLangchainCallbackHandler

### ISSUE THREAD

**Issue by Dev317** [Chainlit/chainlit#306]
Hi,
Is there a way for me to display all the Lanchaing ConversationalRetrievalChain intermediary steps, such as showing prompt, showing combined document in the response message, instead of just displaying the final LLM response?

<img width="1063" alt="image" src="https://github.com/Chainlit/chainlit/assets/70529335/a7dfb660-25cc-4dc8-85b6-c6d51cb580fc">

**Comment by willydouhard** [comment]
We just released version 0.6.3 which comes with a new prompt playground (see [docs](https://docs.chainlit.io/concepts/prompt-playground/overview)). It should work out the box with langchain.

Run `pip install -U chainlit` to upgrade.

**Comment by Dev317** [comment]
I see, thanks for your suggestion. But is there a way to make the AsyncLangchainCallbackHandler to automatically display the verbose chain of thought that can only be seen on terminal? My workaround is basically create another callback class that extends the AsyncLangchainCallbackHandler, and then just pass the intermediary steps to cl.Message to display the whole process

**Comment by willydouhard** [comment]
Can you give a specific example of what information is not picked up by the chainlit callback handler?

**Comment by Dev317** [comment]
<img width="1108" alt="image" src="https://github.com/Chainlit/chainlit/assets/70529335/2d12e7a1-91a7-4e12-8d04-1ad764a8a803">

Between the chain step, it should print out something like this below
![image](https://github.com/Chainlit/chainlit/assets/70529335/7d9b9ea5-baf8-495a-97b5-f32d42fa0453)

**Comment by Dev317** [comment]
At the moment, I was just hardcoding out the callback

<img width="712" alt="image" src="https://github.com/Chainlit/chainlit/assets/70529335/1a4475a0-604d-4712-849f-cec15bec16e4">

**Comment by Dev317** [comment]
I do also encounter this error
`Task exception was never retrieved
future: <Task finished name='Task-3226' coro=<AsyncServer._emit_internal() done, defined at /Users/quangminh.vu/Developer/chatbot/chain_lit_bot/venv/lib/python3.8/site-packages/socketio/asyncio_server.py:427> exception=TypeError('Object of type Message is not JSON serializable')>
Traceback (most recent call last):
  File "/Users/quangminh.vu/.pyenv/versions/3.8.10/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/Users/quangminh.vu/Developer/chatbot/chain_lit_bot/venv/lib/python3.8/site-packages/socketio/asyncio_server.py", line 437, in _emit_internal
    await self._send_packet(sid, self.packet_class(
  File "/Users/quangminh.vu/Developer/chatbot/chain_lit_bot/venv/lib/python3.8/site-packages/socketio/asyncio_server.py", line 442, in _send_packet
    encoded_packet = pkt.encode()
  File "/Users/quangminh.vu/Developer/chatbot/chain_lit_bot/venv/lib/python3.8/site-packages/socketio/packet.py", line 64, in encode
    encoded_packet += self.json.dumps(data, separators=(',', ':'))
  File "/Users/quangminh.vu/.pyenv/versions/3.8.10/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/quangminh.vu/.pyenv/versions/3.8.10/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/quangminh.vu/.pyenv/versions/3.8.10/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/quangminh.vu/.pyenv/versions/3.8.10/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Message is not JSON serializable`

**Comment by willydouhard** [comment]
Do you not see a debug button below the `LLMChain` message with all the prompt information? Like shown here:
https://mintlify.s3-us-west-1.amazonaws.com/chainlit-43/images/open-pp.gif
