### ISSUE TITLE
Cannot run on macOS

### ISSUE THREAD

**Issue by pythiantech** [Chainlit/chainlit#33]
I am using a Macbook pro (M2) Ventura Version 13.3.1
After installing chainlit, when I run `chainlit hello`, this is the error I am getting:

```
dhirajkhanna@Dhirajs-MacBook-Pro chainlit % chainlit hello
2023-06-04 13:07:49 - Created default config file at /Users/dhirajkhanna/Documents/chainlit/.chainlit/config.toml
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/chainlit", line 5, in <module>
    from chainlit.cli import cli
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chainlit/__init__.py", line 8, in <module>
    monkey.patch()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chainlit/lc/monkey.py", line 9, in patch
    import langchain
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/tools/__init__.py", line 36, in <module>
    from langchain.tools.playwright import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/tools/playwright/__init__.py", line 3, in <module>
    from langchain.tools.playwright.click import ClickTool
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/tools/playwright/click.py", line 11, in <module>
    from langchain.tools.playwright.base import BaseBrowserTool
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/tools/playwright/base.py", line 15, in <module>
    from playwright.async_api import Browser as AsyncBrowser
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/async_api/__init__.py", line 25, in <module>
    import playwright.async_api._generated
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 35, in <module>
    from pyee import EventEmitter
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyee/__init__.py", line 120, in <module>
    from pyee.trio import TrioEventEmitter as _TrioEventEmitter  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyee/trio.py", line 7, in <module>
    import trio
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/trio/__init__.py", line 18, in <module>
    from ._core import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/trio/_core/__init__.py", line 27, in <module>
    from ._run import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/trio/_core/_run.py", line 2458, in <module>
    raise NotImplementedError("unsupported platform")
NotImplementedError: unsupported platform
```

**Comment by willydouhard** [comment]
Hello, we have seen a couple of issues when playwright is installed before Chainlit (see https://github.com/Chainlit/chainlit/issues/31). I would recommend that you try to install Chainlit in a venv without playwright to check if that solves the issue.

**Comment by pythiantech** [comment]
Yes it does, thanks
