### ISSUE TITLE
ConnectionRefusedError: You need to configure at least an on_chat_start or an on_message callback

### ISSUE THREAD

**Issue by dpwanjala** [Chainlit/chainlit#510]
Is it just me or is anyone else getting ConnectionRefusedError: You need to configure at least an on_chat_start or an on_message callback with watch-mode enabled. To reproduce.
-run any of the examples with -w enabled
-edit any file and save.
*** app reload and shows the error, in the UI, the input box is now disabled and one can't input anything after this error occurs.

Note. I have both on_chat_start and on_message defined and the apps boots up correctly on first run. Error only occurs once i edit something and it reloads. Thereby I am unable to take advantage of hot-reloading, resorting to painfully restarting the server with any small changes.

ENVIRONMENT
-I am running chainlit in a python environment with python Python 3.10.6 in WSL
-chainlit version = 0.7.40

**Comment by dpwanjala** [comment]
I am running chainlit in a python environment with python Python 3.10.6 in WSL

**Comment by willydouhard** [comment]
I have seen this behavior occur. Will investigate to find the root cause

**Comment by willydouhard** [comment]
Actually I can't reproduce anymore. Are you able to reproduce 100% of the time? If so can you share your code?

**Comment by dpwanjala** [comment]
I am running the simplest example just to simplify and reproduce. Here is the code. All I do is edit the f string and reload.

import chainlit as cl


@cl.on_message
async def main(message: cl.Message):
    # Your custom logic goes here...

    # Send a response back to the user
    await cl.Message(
        content=f"Received: {message.content}",
    ).send()

**Comment by dpwanjala** [comment]
Here is the error logs:

2023-10-31 20:13:43 - Loaded .env file
2023-10-31 20:13:43 - Your app is available at http://localhost:8000
2023-10-31 20:14:19 - 1 change detected
2023-10-31 20:14:19 - File modified: app_chainlit.py. Reloading app...
2023-10-31 20:14:19 - Loaded .env file
message async handler error
Traceback (most recent call last):
  File "/home/dpwanjala/apps/catchmytask-api/venv/lib/python3.10/site-packages/socketio/async_server.py", line 545, in _handle_connect
    success = await self._trigger_event(
  File "/home/dpwanjala/apps/catchmytask-api/venv/lib/python3.10/site-packages/socketio/async_server.py", line 631, in _trigger_event
    ret = await handler(*args)
TypeError: connect() missing 1 required positional argument: 'auth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dpwanjala/apps/catchmytask-api/venv/lib/python3.10/site-packages/engineio/async_server.py", line 475, in run_async_handler
    return await self.handlers[event](*args)
  File "/home/dpwanjala/apps/catchmytask-api/venv/lib/python3.10/site-packages/socketio/async_server.py", line 667, in _handle_eio_message
    await self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/home/dpwanjala/apps/catchmytask-api/venv/lib/python3.10/site-packages/socketio/async_server.py", line 548, in _handle_connect
    success = await self._trigger_event(
  File "/home/dpwanjala/apps/catchmytask-api/venv/lib/python3.10/site-packages/socketio/async_server.py", line 631, in _trigger_event
    ret = await handler(*args)
  File "/home/dpwanjala/apps/catchmytask-api/venv/lib/python3.10/site-packages/chainlit/socket.py", line 51, in connect
    raise ConnectionRefusedError(
ConnectionRefusedError: You need to configure at least an on_chat_start or an on_message callback
2023-10-31 20:14:20 - message async handler error
Traceback (most recent call last):
  File "/home/dpwanjala/apps/catchmytask-api/venv/lib/python3.10/site-packages/socketio/async_server.py", line 545, in _handle_connect
    success = await self._trigger_event(
  File "/home/dpwanjala/apps/catchmytask-api/venv/lib/python3.10/site-packages/socketio/async_server.py", line 631, in _trigger_event
    ret = await handler(*args)
TypeError: connect() missing 1 required positional argument: 'auth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dpwanjala/apps/catchmytask-api/venv/lib/python3.10/site-packages/engineio/async_server.py", line 475, in run_async_handler
    return await self.handlers[event](*args)
  File "/home/dpwanjala/apps/catchmytask-api/venv/lib/python3.10/site-packages/socketio/async_server.py", line 667, in _handle_eio_message
    await self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/home/dpwanjala/apps/catchmytask-api/venv/lib/python3.10/site-packages/socketio/async_server.py", line 548, in _handle_connect
    success = await self._trigger_event(
  File "/home/dpwanjala/apps/catchmytask-api/venv/lib/python3.10/site-packages/socketio/async_server.py", line 631, in _trigger_event
    ret = await handler(*args)
  File "/home/dpwanjala/apps/catchmytask-api/venv/lib/python3.10/site-packages/chainlit/socket.py", line 51, in connect
    raise ConnectionRefusedError(
ConnectionRefusedError: You need to configure at least an on_chat_start or an on_message callback

**Comment by dpwanjala** [comment]
As noted the above error occurs when I am using a python environment but when I am not, I do not get the error and the reload after changes does not break the UI. The issue seems to be when using a python virtual environment on my end.

**Comment by willydouhard** [comment]
Interesting, thank you for the additional information.

**Comment by LarsAC** [comment]
Having the same issue, verbatim copy of the openai-assistant example app. This is with 0.7.602.

**Comment by willydouhard** [comment]
This is only happening with the file watcher (-w)?

**Comment by LarsAC** [comment]
No, this is also with plain run command (no args)

**Comment by willydouhard** [comment]
Can you share your app file?

**Comment by LarsAC** [comment]
Downgraded to 0.7.500 and it worked, now went back to 0.7.603 and still works. Not sure what happened.

**Comment by umarbutler** [comment]
I have encountered this error, also using `venv` with an extremely basic config.

**Comment by willydouhard** [comment]
I am not sure why it is happening but reseting the venv seems to fix the issue
