### ISSUE TITLE
AttributeError after upgrading to new version

### ISSUE THREAD

**Issue by okabe-sama** [Chainlit/chainlit#520]
I am trying to set up a RAG application with langchain - FAISS vector store, LlamaCpp model. I have attached a dummy code snippet to reproduce the error.

The below code works fine for chainlit **v0.7.0**. However, it started giving error (stack trace attached) when I upgraded to **v0.7.400**.

**Code snippet:**
```
import chainlit as cl
from langchain.vectorstores import FAISS
from langchain.llms import LlamaCpp
from langchain.chains import RetrievalQA

def load_vectorstore():
   # load and return the vectorstore using FAISS
   return vstore

def load_llm():
   # load and return the LLM using LlamaCpp
   return llm

def create_chain():
   db = load_vectorstore()
   llm = load_llm()
   chain = RetrievalQA.from_chain_type(llm=llm, retriever=db.as_retriever())
   return chain

@cl.on_chat_start
async def start():
   chain = create_chain()
   cl.user_session.set("chain", chain)

@cl.on_message
async def main(message):
   chain = cl.user_session.get("chain")
   answer = await cl.make_async(chain)(message)
   await cl.Message(content=answer).send()
```

**Error stack trace:**
```
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/chainlit/utils.py", line 39, in wrapper
    return await user_function(**params_values)
  File "/app/model.py", line 161, in main
    answer = await cl.make_async(chain)(message)
  File "/app/lib/python3.8/site-packages/asyncer/_main.py", line 358, in wrapper
    return await anyio.to_thread.run_sync(
  File "/app/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/app/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/.pyenv/versions/3.8.10/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/.pyenv/versions/3.8.10/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/.pyenv/versions/3.8.10/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/app/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/lib/python3.8/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/app/lib/python3.8/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/app/lib/python3.8/site-packages/langchain/chains/retrieval_qa/base.py", line 136, in _call
    docs = self._get_docs(question, run_manager=_run_manager)
  File "/app/lib/python3.8/site-packages/langchain/chains/retrieval_qa/base.py", line 216, in _get_docs
    return self.retriever.get_relevant_documents(
  File "/app/lib/python3.8/site-packages/langchain/schema/retriever.py", line 211, in get_relevant_documents
    raise e
  File "/app/lib/python3.8/site-packages/langchain/schema/retriever.py", line 204, in get_relevant_documents
    result = self._get_relevant_documents(
  File "/app/lib/python3.8/site-packages/langchain/schema/vectorstore.py", line 657, in _get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/app/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 509, in similarity_search
    docs_and_scores = self.similarity_search_with_score(
  File "/app/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 390, in similarity_search_with_score
    embedding = self._embed_query(query)
  File "/app/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 153, in _embed_query
    return self.embedding_function.embed_query(text)
  File "/app/lib/python3.8/site-packages/langchain/embeddings/huggingface.py", line 105, in embed_query
    return self.embed_documents([text])[0]
  File "/app/lib/python3.8/site-packages/langchain/embeddings/huggingface.py", line 86, in embed_documents
    texts = list(map(lambda x: x.replace("\n", " "), texts))
  File "/app/lib/python3.8/site-packages/langchain/embeddings/huggingface.py", line 86, in <lambda>
    texts = list(map(lambda x: x.replace("\n", " "), texts))
AttributeError: 'Message' object has no attribute 'replace'
```

**Version details:**
```
OS: Ubuntu 22.04
Python: 3.8.10
Packages:
chainlit==0.7.400
langchain==0.0.327
```

**Comment by willydouhard** [comment]
Hello, on_message now takes a `cl.Message` instead of a string. So you should pass `message.content` to your agent.
