### ISSUE TITLE
0.7.301+ KeyError: 'message' #502

### ISSUE THREAD

**Issue by ggnicolau** [Chainlit/chainlit#535]
Hi. I can run my app using Chainlit up to version 7.2. After that, I keep getting KeyError: 'message'. I've tried all recent versions and none works.
```
2023-11-10 16:09:13 - Your app is available at http://localhost:8000/
gio: http://localhost:8000/: Operation not supported
GPU availability: False
2023-11-10 16:09:16 - Load pretrained SentenceTransformer: BAAI/bge-base-en
2023-11-10 16:09:22 - 'message'
Traceback (most recent call last):
File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/chainlit/socket.py", line 174, in process_message
message = await context.emitter.process_user_message(payload)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/chainlit/emitter.py", line 153, in process_user_message
message_dict = payload["message"]
~~~~~~~^^^^^^^^^^^
KeyError: 'message'
```

If it helps, I can share my code:

```
@on_chat_start
def init():
    llm = AzureChatOpenAI(
        deployment_name=Constants.AZURE_OPENAI_DEPLOYMENT_NAME,
        model_name=Constants.AZURE_OPENAI_MODEL_NAME,
        openai_api_base=Constants.AZURE_OPENAI_DEPLOYMENT_ENDPOINT,
        openai_api_version=Constants.AZURE_OPENAI_DEPLOYMENT_VERSION,
        openai_api_key=Constants.AZURE_OPENAI_API_KEY,
        openai_api_type=Constants.AZURE_OPEN_API_TYPE,
        temperature=Constants.TEMPERATURE,
        streaming=True, 
        callbacks=[StreamingStdOutCallbackHandler()],
    )

    print("GPU availability:", torch.cuda.is_available())
    embeddings = HuggingFaceEmbeddings(
        model_name = "BAAI/bge-base-en", 
        model_kwargs = {"device": "cuda" if torch.cuda.is_available() else "cpu"},
        encode_kwargs = {"normalize_embeddings": True} 
    )
    

    # connect to the vector database
    client = QdrantClient(
            host=Constants.QDRANT_HOSTNAME,
            port=Constants.QDRANT_PORT,
        )

    doc_store = Qdrant(
        client=client, collection_name="plano_diretor", embeddings=embeddings
    )

    retriever = doc_store.as_retriever(
        search_type="similarity_score_threshold",
        search_kwargs={"score_threshold": 0.5, "k": 5},
    ) 

    messages = [
        SystemMessagePromptTemplate.from_template(CustomPrompts.THIRD_CITATION_TEMPLATE)
    ]
    messages.append(HumanMessagePromptTemplate.from_template("{question}"))
    smart_prompt = ChatPromptTemplate.from_messages(messages)

    question_generator = LLMChain(
        llm=llm,
        prompt=CONDENSE_QUESTION_PROMPT,  
        verbose=True,
    )

    doc_chain = load_qa_with_sources_chain(
        llm=llm,
        chain_type="stuff",
        prompt=smart_prompt ,
        verbose=True,
    )

    memory = ConversationKGMemory( 
        llm=llm,
        memory_key="chat_history",
        return_messages=True,
        input_key="question",
        output_key="answer",  #
        max_token_limit=3000,
        k=5,
    )

    conversational_chain = ConversationalRetrievalChain(
        retriever=retriever,
        question_generator=question_generator,
        combine_docs_chain=doc_chain,
        memory=memory,
        rephrase_question=False,
        return_source_documents=True,
        verbose=True,
    )

    # Set chain as a user session variable
    cl.user_session.set("conversation_chain", conversational_chain)


@on_message
async def main(message: str):
    chat_history = []

    # Read chain from user session variable
    chain = cl.user_session.get("conversation_chain")
    # Run the chain asynchronously with an async callback
    res = chain({"question": message, "chat_history": chat_history})

    sources = [doc.metadata.get("source") for doc in res["source_documents"]]

    # Send the answer and the text elements to the UI
    await cl.Message(
        content=f"ANSWER: {res['answer']}, \n\nSOURCES: {set(sources)}"
    ).send()
```

**Comment by willydouhard** [comment]
Are you using the official chainlit UI or did you fork/modified it?

**Comment by ggnicolau** [comment]
@willydouhard it's the official chainlit UI. I just pip installed and ran this pieace of code. It works up to 0.7.2. I tried in a new clean miniconda environment and the error persist. Right now, I chose to run my app always on version 0.7.2, but I would prefer to keep it up to date.

**Comment by willydouhard** [comment]
`on_message` now takes a `cl.Message` instead of a `str`. Try to update the code to:

```py
@on_message
async def main(message: cl.Message):
    chat_history = []

    # Read chain from user session variable
    chain = cl.user_session.get("conversation_chain")
    # Run the chain asynchronously with an async callback
    res = chain({"question": message.content, "chat_history": chat_history})

    sources = [doc.metadata.get("source") for doc in res["source_documents"]]

    # Send the answer and the text elements to the UI
    await cl.Message(
        content=f"ANSWER: {res['answer']}, \n\nSOURCES: {set(sources)}"
    ).send()
    ```

**Comment by ggnicolau** [comment]
Ok, thank you! I think we're almost there, but now I've got error:

```
2023-11-13 10:28:03 - File modified: saci_ui_stuff.py. Reloading app...
GPU availability: False
2023-11-13 10:28:04 - Load pretrained SentenceTransformer: BAAI/bge-base-en
GPU availability: False
2023-11-13 10:28:05 - Load pretrained SentenceTransformer: BAAI/bge-base-en
GPU availability: False
2023-11-13 10:28:05 - Load pretrained SentenceTransformer: BAAI/bge-base-en


> Entering new RetrievalQA chain...
2023-11-13 10:28:15 - 'Message' object has no attribute 'replace'
Traceback (most recent call last):
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/chainlit/utils.py", line 39, in wrapper
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/gnicolau/Documents/bitbucket/saci-nlp/ui/saci_ui_stuff_u.py", line 141, in main
    res = chain({"query": question},return_only_outputs=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 136, in _call
    docs = self._get_docs(question, run_manager=_run_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 216, in _get_docs
    return self.retriever.get_relevant_documents(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/schema/retriever.py", line 211, in get_relevant_documents
    raise e
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/schema/retriever.py", line 204, in get_relevant_documents
    result = self._get_relevant_documents(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/schema/vectorstore.py", line 660, in _get_relevant_documents
    self.vectorstore.similarity_search_with_relevance_scores(
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/schema/vectorstore.py", line 306, in similarity_search_with_relevance_scores
    docs_and_similarities = self._similarity_search_with_relevance_scores(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/vectorstores/qdrant.py", line 1882, in _similarity_search_with_relevance_scores
    return self.similarity_search_with_score(query, k, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/vectorstores/qdrant.py", line 351, in similarity_search_with_score
    self._embed_query(query),
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/vectorstores/qdrant.py", line 1988, in _embed_query
    embedding = self.embeddings.embed_query(query)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 105, in embed_query
    return self.embed_documents([text])[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 86, in embed_documents
    texts = list(map(lambda x: x.replace("\n", " "), texts))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ggnicolau/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 86, in <lambda>
    texts = list(map(lambda x: x.replace("\n", " "), texts))
                               ^^^^^^^^^
AttributeError: 'Message' object has no attribute 'replace'
```

I tried to debug, but I couldn't figure out exactly what's happening here.

**Comment by willydouhard** [comment]
```py
  res = chain({"query": question},return_only_outputs=True)
  ```
  Here question is probably a `cl.Message` instead of a string. Try to passe the content value of the message instead.

**Comment by ggnicolau** [comment]
Solved. Thank you!
