### ISSUE TITLE
cannot use chainlit context in fast api 

### ISSUE THREAD

**Issue by codingmoh** [Chainlit/chainlit#548]
I get this error when trying to call   init_http_context() in a fast api route:

my code:

```
import chainlit as cl
from chainlit.server import app
from chainlit.user_session import user_sessions
from chainlit.context import init_http_context
from llm_query_service import LLMQueryService

load_dotenv('.env')
PROMPT_FILE=os.environ['PROMPT_FILE']


@app.get("/messages")
def get_messages(request: Request):
    init_http_context()
    return cl.user_session.get("message_history")
```

The error:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/app.py", line 20, in get_messages
    init_http_context()
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/chainlit/context.py", line 60, in init_http_context
    context = ChainlitContext(session)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/codingmo/Documents/Projects/genius/genius-backend-1/env/lib/python3.11/site-packages/chainlit/context.py", line 28, in __init__
    self.loop = asyncio.get_running_loop()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
```

**Comment by willydouhard** [comment]
Did you start your server with `chainlit run ...` or `python ...`? Also the user_session represents a websocket session. You can access a user_session from an http request if you know the session id. However the http request will not have its own user session.

**Comment by codingmoh** [comment]
Thanks for the quick response!
I started the app with `chainlit run` - should I've used `python -m chainlit run` or should I've added a custom event loop?

Actually our goal is to iterate over all active sessions, and _showcase some_ of them on an active board.

**Comment by willydouhard** [comment]
Using `chainlit run` is correct. I can't reproduce, running the examples of the documention work on my end:

```py
from chainlit.server import app
from fastapi import Request
from fastapi.responses import (
    HTMLResponse,
)

from chainlit.context import init_http_context
import chainlit as cl


@app.get("/hello")
async def hello(
    request: Request,
):
    init_http_context()
    await cl.Message(content="Hello World").send()
    return HTMLResponse("Hello World")


@cl.on_chat_start
async def start():
    await cl.Message(content="Hello World").send()
```

What version of Chainlit are you using?

**Comment by codingmoh** [comment]
Did you manage to fire a get request? - then chainlit app does start, but whenever I'm firing the request, I get this error

Also, I am using the newest version, 0.7.603 - but been trying with different ones, and having the same error

**Comment by codingmoh** [comment]
@willydouhard - OK, I tried running your code and it works BUT when I remove the async operation and have a sync method - I get the same exception with the same error



```
@app.get("/hello")
def hello(
    request: Request,
):
    init_http_context()
    return HTMLResponse("Hello World")
```

**Comment by willydouhard** [comment]
Okay so we should be more explicit about the necessity of the async keyword right?

**Comment by codingmoh** [comment]
I think so - highlighting that would definitely be helpful, since fastAPI endpoint functions do not necessarily have to be asynchronous

**Comment by codingmoh** [comment]
Also, thank you so much for your help and support 🙏
