### ISSUE TITLE
peer closed connection without sending complete message body occurred when use different session to send msg at same time

### ISSUE THREAD

**Issue by Mrfranken** [Chainlit/chainlit#564]
background:
1. I used llama2 as backend for inferenceing
2. ust chanlit to start a frontend for user.

And I created two users, then I logined with user in different browser.

If one session was inferencing now, and I send msg in another session, it will raise error as above.

Sir, Could you help with this?
Or could you teach me how to use different users to chat with my local llm and sessions do not influence each other?

Many thx

```
import json
from typing import Optional

import chainlit as cl
from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
from langchain.schema import StrOutputParser
from langchain.schema.runnable import Runnable
from langchain.schema.runnable.config import RunnableConfig



@cl.set_chat_profiles
async def chat_profile(current_user: cl.AppUser):
    if "admin_user" not in current_user.tags:
        # Default to 3.5 when not admin
        return [
            cl.ChatProfile(
                name="GPT-3.5",
                markdown_description="The underlying LLM model is **GPT-3.5**.",
                icon="https://picsum.photos/200",
            )
        ]

    return [
        cl.ChatProfile(
            name="GPT-3.5",
            markdown_description="The underlying LLM model is **GPT-3.5**.",
            icon="https://picsum.photos/200",
        ),
        cl.ChatProfile(
            name="GPT-4",
            markdown_description="The underlying LLM model is **GPT-4**.",
            icon="https://picsum.photos/250",
        ),
    ]


@cl.password_auth_callback
def auth_callback(username: str, password: str) -> Optional[cl.AppUser]:
    auth = None
    with open('authentication.json', 'r') as f:
        auth = json.load(f)
    if (username, password) == ("admin", "admin"):
        return cl.AppUser(
            username="admin", role="ADMIN", provider="credentials", tags=["admin_user"]
        )
    elif username == auth.get(username, None):
        return cl.AppUser(
            username=username, role="USER", provider="credentials", tags=["regular_user"]
        )
    else:
        return None


@cl.on_chat_start
async def on_chat_start():
    app_user = cl.user_session.get("user")
    chat_profile = cl.user_session.get("chat_profile")
    print(chat_profile)
    await cl.Message(
        content=f"starting chat with {app_user.username} using the {chat_profile} chat profile"
    ).send()

    model = ChatOpenAI(
        temperature=0.0,
        openai_api_base="xxx",
        openai_api_key="xxx",
        max_tokens=500,
        streaming=True
    )
    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                # "You're a very knowledgeable historian who provides accurate and eloquent answers to historical questions.",
                "You're a Linux expert who provides accurate and eloquent answers to Linux system related questions. Only answer the question about Linux"
            ),
            ("human", "{question}"),
        ]
    )
    print(id(model))
    runnable = prompt | model | StrOutputParser()
    cl.user_session.set(app_user.username, runnable)


@cl.on_message
async def on_message(message: cl.Message):
    runnable = cl.user_session.get(message.author)  # type: Runnable

    msg = cl.Message(content="")

    async for chunk in runnable.astream(
            {"question": message.content},
            config=RunnableConfig(callbacks=[cl.LangchainCallbackHandler()]),
    ):
        await msg.stream_token(chunk)
```

**Comment by Mrfranken** [comment]
```
import json
from typing import Optional

import chainlit as cl
from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
from langchain.schema import StrOutputParser
from langchain.schema.runnable import Runnable
from langchain.schema.runnable.config import RunnableConfig



@cl.set_chat_profiles
async def chat_profile(current_user: cl.AppUser):
    if "admin_user" not in current_user.tags:
        # Default to 3.5 when not admin
        return [
            cl.ChatProfile(
                name="GPT-3.5",
                markdown_description="The underlying LLM model is **GPT-3.5**.",
                icon="https://picsum.photos/200",
            )
        ]

    return [
        cl.ChatProfile(
            name="GPT-3.5",
            markdown_description="The underlying LLM model is **GPT-3.5**.",
            icon="https://picsum.photos/200",
        ),
        cl.ChatProfile(
            name="GPT-4",
            markdown_description="The underlying LLM model is **GPT-4**.",
            icon="https://picsum.photos/250",
        ),
    ]


@cl.password_auth_callback
def auth_callback(username: str, password: str) -> Optional[cl.AppUser]:
    auth = None
    with open('authentication.json', 'r') as f:
        auth = json.load(f)
    if (username, password) == ("admin", "admin"):
        return cl.AppUser(
            username="admin", role="ADMIN", provider="credentials", tags=["admin_user"]
        )
    elif username == auth.get(username, None):
        return cl.AppUser(
            username=username, role="USER", provider="credentials", tags=["regular_user"]
        )
    else:
        return None


@cl.on_chat_start
async def on_chat_start():
    app_user = cl.user_session.get("user")
    chat_profile = cl.user_session.get("chat_profile")
    print(chat_profile)
    await cl.Message(
        content=f"starting chat with {app_user.username} using the {chat_profile} chat profile"
    ).send()

    model = ChatOpenAI(
        temperature=0.0,
        openai_api_base="xxx",
        openai_api_key="xxx",
        max_tokens=500,
        streaming=True
    )
    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                # "You're a very knowledgeable historian who provides accurate and eloquent answers to historical questions.",
                "You're a Linux expert who provides accurate and eloquent answers to Linux system related questions. Only answer the question about Linux"
            ),
            ("human", "{question}"),
        ]
    )
    print(id(model))
    runnable = prompt | model | StrOutputParser()
    cl.user_session.set(app_user.username, runnable)


@cl.on_message
async def on_message(message: cl.Message):
    runnable = cl.user_session.get(message.author)  # type: Runnable

    msg = cl.Message(content="")

    async for chunk in runnable.astream(
            {"question": message.content},
            config=RunnableConfig(callbacks=[cl.LangchainCallbackHandler()]),
    ):
        await msg.stream_token(chunk)
```

**Comment by willydouhard** [comment]
Hello, thank you for the reproducible snippet of code.

You mention llama2 but your example use openai. I ran that code in two separate windows and was not able to reproduce.

Is this also happening with openai on your end? Also what version of Chainlit are you using?

**Comment by Mrfranken** [comment]
sorry I  gave misunderstanding info, acutally, when I run this snippt of codes, I will change the "openai_api_base" to backend service url which was based on llama-cpp-python that can provide service based on llama2 and llama.cpp library

**Comment by willydouhard** [comment]
Ah I see. Is that endpoint able to handle concurrent requests (even without chainlit)? Also what version of Chainlit are you using?

**Comment by Mrfranken** [comment]
<img width="1914" alt="iShot_2023-11-23_21 56 47" src="https://github.com/Chainlit/chainlit/assets/18159666/c99d6187-7ec2-4055-91c8-b3cb839c67a0">

```
Traceback (most recent call last):
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/chainlit/utils.py", line 39, in wrapper
    return await user_function(**params_values)
  File "/Users/vince/Downloads/myworkspace/llm/llm/chainlit_test/profile/app.py", line 107, in on_message
    async for chunk in runnable.astream(
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/runnable/base.py", line 1578, in astream
    async for chunk in self.atransform(input_aiter(), config, **kwargs):
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/runnable/base.py", line 1564, in atransform
    async for chunk in self._atransform_stream_with_config(
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/runnable/base.py", line 1015, in _atransform_stream_with_config
    async for chunk in iterator:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/runnable/base.py", line 1537, in _atransform
    async for output in final_pipeline:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/output_parser.py", line 343, in atransform
    async for chunk in self._atransform_stream_with_config(
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/runnable/base.py", line 1015, in _atransform_stream_with_config
    async for chunk in iterator:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/output_parser.py", line 321, in _atransform
    async for chunk in input:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/utils/aiter.py", line 97, in tee_peer
    item = await iterator.__anext__()
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/schema/runnable/base.py", line 564, in atransform
    async for output in self.astream(final, config, **kwargs):
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/chat_models/base.py", line 273, in astream
    raise e
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/chat_models/base.py", line 262, in astream
    async for chunk in self._astream(
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 405, in _astream
    async for chunk in await acompletion_with_retry(
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 232, in <genexpr>
    return (
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/openai/api_requestor.py", line 396, in wrap_resp
    async for r in resp:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/openai/api_requestor.py", line 724, in <genexpr>
    return (
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/openai/api_requestor.py", line 123, in parse_stream_async
    async for line in rbody:
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/aiohttp/streams.py", line 35, in __anext__
    rv = await self.read_func()
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/aiohttp/streams.py", line 311, in readline
    return await self.readuntil()
  File "/Users/vince/miniconda3/envs/python310env/lib/python3.10/site-packages/aiohttp/streams.py", line 319, in readuntil
    raise self._exception
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
2023-11-23 21:50:25 - message='OpenAI API response' path=http://localhost:8000/v1/chat/completions processing_ms=209 request_id=bf9c7d42a14243dc8c6e2ec933cb843c response_code=200
```
version: 
chainlit     0.7.400
langchain 0.0.330

**Comment by Mrfranken** [comment]
> Ah I see. Is that endpoint able to handle concurrent requests (even without chainlit)? Also what version of Chainlit are you using?

yes, the endpoint can recive two requests at one time(it is based on fastapi), but give inferencing outcome one by one.

**Comment by willydouhard** [comment]
Yes, can you try to update Chainlit, we fixed this bug in the latest release I believe. `pip install -U chainlit`

**Comment by Mrfranken** [comment]
hi, I update chainlit to 0.7.604 and langchain to 0.0.340, issue still exist.
And I tried use openai endpoint for instead, everything works well.

**Comment by willydouhard** [comment]
I see, what version of OpenAI are you using?

**Comment by willydouhard** [comment]
It looks to me the issue is coming from OpenAI. [Similar issues](https://github.com/openai/openai-python/issues?q=is%3Aissue+Response+payload+is+not+completed+is%3Aclosed) have been opened.

**Comment by Mrfranken** [comment]
issue solved due to othere lib error, thx for your time @willydouhard
