### ISSUE TITLE
chainlit 1.0.0rc3 fails to sync with chainlit cloud

### ISSUE THREAD

**Issue by SalamanderXing** [Chainlit/chainlit#625]
Im working with the development version of chainlit==1.0.0rc3 and when I enable feedback I get these error messages:

```
2024-01-02 15:27:32 - HTTP Request: POST https://cloud.chainlit.io/api/graphql "HTTP/1.1 200 OK"
2024-01-02 15:27:32 - HTTP Request: POST https://cloud.chainlit.io/api/graphql "HTTP/1.1 200 OK"
2024-01-02 15:27:32 - Failed to send steps: [{'message': 'Unknown type "StepType". Did you mean "__Type"?', 'locations': [{'line': 4, 'column': 18}]}, {'message': 'Unknown type "GenerationPayloadInput".', 'locations': [{'line': 12, 'column': 24}]}, {'message': 'Unknown type "FeedbackPayloadInput".', 'locations': [{'line': 13, 'column': 22}]}, {'message': 'Unknown type "AttachmentPayloadInput".', 'locations': [{'line': 14, 'column': 26}]}, {'message': 'Cannot query field "ingestStep" on type "Mutation".', 'locations': [{'line': 17, 'column': 7}]}]
2024-01-02 15:27:32 - Failed to send steps: [{'message': 'Unknown type "StepType". Did you mean "__Type"?', 'locations': [{'line': 4, 'column': 18}]}, {'message': 'Unknown type "GenerationPayloadInput".', 'locations': [{'line': 12, 'column': 24}]}, {'message': 'Unknown type "FeedbackPayloadInput".', 'locations': [{'line': 13, 'column': 22}]}, {'message': 'Unknown type "AttachmentPayloadInput".', 'locations': [{'line': 14, 'column': 26}]}, {'message': 'Cannot query field "ingestStep" on type "Mutation".', 'locations': [{'line': 17, 'column': 7}]}]
2024-01-02 15:27:32 - Failed to send steps: [{'message': 'Unknown type "StepType". Did you mean "__Type"?', 'locations': [{'line': 4, 'column': 18}]}, {'message': 'Unknown type "GenerationPayloadInput".', 'locations': [{'line': 12, 'column': 24}]}, {'message': 'Unknown type "FeedbackPayloadInput".', 'locations': [{'line': 13, 'column': 22}]}, {'message': 'Unknown type "AttachmentPayloadInput".', 'locations': [{'line': 14, 'column': 26}]}, {'message': 'Cannot query field "ingestStep" on type "Mutation".', 'locations': [{'line': 17, 'column': 7}]}]
2024-01-02 15:27:32 - Failed to send steps: [{'message': 'Unknown type "StepType". Did you mean "__Type"?', 'locations': [{'line': 4, 'column': 18}]}, {'message': 'Unknown type "GenerationPayloadInput".', 'locations': [{'line': 12, 'column': 24}]}, {'message': 'Unknown type "FeedbackPayloadInput".', 'locations': [{'line': 13, 'column': 22}]}, {'message': 'Unknown type "AttachmentPayloadInput".', 'locations': [{'line': 14, 'column': 26}]}, {'message': 'Cannot query field "ingestStep" on type "Mutation".', 'locations': [{'line': 17, 'column': 7}]}]
2024-01-02 15:27:33 - HTTP Request: POST https://cloud.chainlit.io/api/graphql "HTTP/1.1 200 OK"
2024-01-02 15:27:33 - Failed to create feedback: [{'message': 'Unknown type "FeedbackStrategy".', 'locations': [{'line': 5, 'column': 24}]}, {'message': 'Cannot query field "createFeedback" on type "Mutation". Did you mean "createMessage"?', 'locations': [{'line': 8, 'column': 13}]}]
2024-01-02 15:27:33 - Failed to create feedback: [{'message': 'Unknown type "FeedbackStrategy".', 'locations': [{'line': 5, 'column': 24}]}, {'message': 'Cannot query field "createFeedback" on type "Mutation". Did you mean "createMessage"?', 'locations': [{'line': 8, 'column': 13}]}]
2024-01-02 15:27:34 - HTTP Request: POST https://cloud.chainlit.io/api/graphql "HTTP/1.1 200 OK"
2024-01-02 15:27:34 - Failed to upsert thread: [{'message': 'Cannot query field "upsertThread" on type "Mutation".', 'locations': [{'line': 9, 'column': 13}]}]
2024-01-02 15:27:34 - Failed to upsert thread: [{'message': 'Cannot query field "upsertThread" on type "Mutation".', 'locations': [{'line': 9, 'column': 13}]}]
disconnect async handler error
Traceback (most recent call last):
  File "/home/bluesk/Documents/gcp-chatbot/chainlit/lib/python3.11/site-packages/chainlit_client/api.py", line 210, in make_api_call
    raise_error(json["errors"])
  File "/home/bluesk/Documents/gcp-chatbot/chainlit/lib/python3.11/site-packages/chainlit_client/api.py", line 194, in raise_error
    raise Exception(error)
Exception: [{'message': 'Cannot query field "upsertThread" on type "Mutation".', 'locations': [{'line': 9, 'column': 13}]}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bluesk/Documents/gcp-chatbot/chainlit/lib/python3.11/site-packages/engineio/async_server.py", line 475, in run_async_handler
    return await self.handlers[event](*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bluesk/Documents/gcp-chatbot/chainlit/lib/python3.11/site-packages/socketio/async_server.py", line 687, in _handle_eio_disconnect
    await self._handle_disconnect(eio_sid, n)
  File "/home/bluesk/Documents/gcp-chatbot/chainlit/lib/python3.11/site-packages/socketio/async_server.py", line 575, in _handle_disconnect
    await self._trigger_event('disconnect', namespace, sid)
  File "/home/bluesk/Documents/gcp-chatbot/chainlit/lib/python3.11/site-packages/socketio/async_server.py", line 631, in _trigger_event
    ret = await handler(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/bluesk/Documents/gcp-chatbot/chainlit/lib/python3.11/site-packages/chainlit/socket.py", line 178, in disconnect
    await persist_user_session(session.thread_id, session.to_persistable())
  File "/home/bluesk/Documents/gcp-chatbot/chainlit/lib/python3.11/site-packages/chainlit/socket.py", line 32, in persist_user_session
    await data_layer.update_thread(thread_id=thread_id, metadata=metadata)
  File "/home/bluesk/Documents/gcp-chatbot/chainlit/lib/python3.11/site-packages/chainlit/data/__init__.py", line 373, in update_thread
    await self.client.api.upsert_thread(
  File "/home/bluesk/Documents/gcp-chatbot/chainlit/lib/python3.11/site-packages/chainlit_client/api.py", line 460, in upsert_thread
    thread = await self.make_api_call("upsert thread", query, variables)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bluesk/Documents/gcp-chatbot/chainlit/lib/python3.11/site-packages/chainlit_client/api.py", line 214, in make_api_call
    raise_error(error)
  File "/home/bluesk/Documents/gcp-chatbot/chainlit/lib/python3.11/site-packages/chainlit_client/api.py", line 194, in raise_error
    raise Exception(error)
```

The chat and feedbacks do not get synced with the cloud and responses are also slowed down. Cloud works as expected if I use chainlit 0.7.700.

**Comment by willydouhard** [comment]
This is expected. The release candidate is built to work with the new Chainlit platform (which will be released this week).
