### ISSUE TITLE
Error running Llama Index example code

### ISSUE THREAD

**Issue by reno77** [Chainlit/chainlit#643]
I tried running the code from https://docs.chainlit.io/integrations/llama-index

I initially got an error message for line 12 :
`from langchain.chat_models import ChatOpenAI`

fixed it by changing the line to:
`from langchain_community.chat_models import ChatOpenAI`

But after that i got the following error : 

`LLMPredictor is deprecated, please use LLM instead.
2024-01-08 20:58:51 - 'NoneType' object has no attribute 'context_window'
Traceback (most recent call last):
  File "/home/rama/miniconda3/envs/mixtral/lib/python3.9/site-packages/chainlit/utils.py", line 39, in wrapper
    return await user_function(**params_values)
  File "app.py", line 40, in factory
    service_context = ServiceContext.from_defaults(
  File "/home/rama/miniconda3/envs/mixtral/lib/python3.9/site-packages/llama_index/service_context.py", line 191, in from_defaults
    prompt_helper = prompt_helper or _get_default_prompt_helper(
  File "/home/rama/miniconda3/envs/mixtral/lib/python3.9/site-packages/llama_index/service_context.py", line 52, in _get_default_prompt_helper
    return PromptHelper.from_llm_metadata(llm_metadata=llm_metadata)
  File "/home/rama/miniconda3/envs/mixtral/lib/python3.9/site-packages/llama_index/indices/prompt_helper.py", line 118, in from_llm_metadata
    context_window = llm_metadata.context_window
AttributeError: 'NoneType' object has no attribute 'context_window'
LLMPredictor is deprecated, please use LLM instead.
2024-01-08 20:58:51 - 'NoneType' object has no attribute 'context_window'
Traceback (most recent call last):
  File "/home/rama/miniconda3/envs/mixtral/lib/python3.9/site-packages/chainlit/utils.py", line 39, in wrapper
    return await user_function(**params_values)
  File "app.py", line 40, in factory
    service_context = ServiceContext.from_defaults(
  File "/home/rama/miniconda3/envs/mixtral/lib/python3.9/site-packages/llama_index/service_context.py", line 191, in from_defaults
    prompt_helper = prompt_helper or _get_default_prompt_helper(
  File "/home/rama/miniconda3/envs/mixtral/lib/python3.9/site-packages/llama_index/service_context.py", line 52, in _get_default_prompt_helper
    return PromptHelper.from_llm_metadata(llm_metadata=llm_metadata)
  File "/home/rama/miniconda3/envs/mixtral/lib/python3.9/site-packages/llama_index/indices/prompt_helper.py", line 118, in from_llm_metadata
    context_window = llm_metadata.context_window
AttributeError: 'NoneType' object has no attribute 'context_window'
`

**Comment by willydouhard** [comment]
Does it work if you downgrade langchain? They might have release breaking changes and all libraries might not be up to date?

**Comment by reno77** [comment]
> Does it work if you downgrade langchain? They might have release breaking changes and all libraries might not be up to date?

Ah, yups. Using a previous langchain (I tried 0.0.340) fixed the issue . 
Thanks!
