### ISSUE TITLE
Issue with LiteralAI

### ISSUE THREAD

**Issue by brestok-1** [Chainlit/chainlit#753]
When I try to initialize chainlit app, I got this error:

2024-02-20 10:41:37 - HTTP Request: POST https://cloud.getliteral.ai/api/graphql "HTTP/1.1 404 Not Found"
2024-02-20 10:41:37 - Failed to get user session: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>404 Page not found</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Page not found</h1>
<h2>The requested URL was not found on this server.</h2>
<h2></h2>
</body></html>

2024-02-20 10:41:57 - HTTP Request: POST https://cloud.getliteral.ai/api/graphql "HTTP/1.1 404 Not Found"
2024-02-20 10:41:57 - Task exception was never retrieved
future: <Task finished name='Task-119' coro=<ChainlitDataLayer.create_user_session() done, defined at /home/maksim/.local/lib/python3.10/site-packages/chainlit/data/__init__.py:423> exception=Exception('\n<html><head>\n<meta http-equiv="content-type" content="text/html;charset=utf-8">\n<title>404 Page not found</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Page not found</h1>\n<h2>The requested URL was not found on this server.</h2>\n<h2></h2>\n</body></html>\n')>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/home/maksim/.local/lib/python3.10/site-packages/chainlit/data/__init__.py", line 430, in create_user_session
    existing_session = await self.client.api.get_user_session(id=id)
  File "/home/maksim/.local/lib/python3.10/site-packages/literalai/api.py", line 708, in get_user_session
    result = await self.make_api_call("get user session", query, variables)
  File "/home/maksim/.local/lib/python3.10/site-packages/literalai/api.py", line 217, in make_api_call
    raise_error(response.text)
  File "/home/maksim/.local/lib/python3.10/site-packages/literalai/api.py", line 206, in raise_error
    raise Exception(error)
    
  I think it related to some updates on LiteralAI. I used the last version of chainlit

**Comment by willydouhard** [comment]
We had a migration ongoing this morning (check on discord if you want more infos). Should be back up, don't forget to update your Chainlit installation `pip install -U chainlit`!
