### ISSUE TITLE
No module named 'openai' error on fresh install

### ISSUE THREAD

**Issue by nmstoker** [Chainlit/chainlit#754]
For reasons, I'm not able to raise this with the full level of detail I would normally prefer to include, but I'll post it just in case others see this too.

I've just installed chainlit 1.0.301 into a conda env, nstalled via pip. Upon trying `chainlit init` or `chainlit hello` both error out with a traceback that ends in:

**ModuleNotFoundError: No module named 'openai'**

(I've had to retype that as I don't have access to paste the error plus other info here, however I believe I've done it w/o typos!

I didn't get this on another install done in the same way two days ago which installed 1.0.200.

Nothing else was done in the recent case, hence I'm wondering if it's a small reversion in one of the two recent releases since 1.0.200.

Edit: Sorry, missed out this is on Windows. Python version 3.11.8 in the conda env.

**Comment by nmstoker** [comment]
In fact, having switched it back to installing 1.0.200 in that same environment, it now does **not** give the error, so it does seem to be a recent change.

**Comment by willydouhard** [comment]
Chainlit has no dependency to openai has you can see [here](https://github.com/Chainlit/chainlit/blob/main/backend/pyproject.toml#L54). It only has a dependency to openai when running in the CI.

The reason is that we do not want to bloat the package with all the third party packages, it is up to the developer to selectively install those.

**Comment by moritalous** [comment]
I also encountered the same error.
It seems that the error occurs not with chainlit but with literalai, which has a dependency.
I don't know the maintainer of this library, do you know their contact information?

```shell
vscode ➜ ~ $ cd tmp/
vscode ➜ ~/tmp $ poetry init
vscode ➜ ~/tmp $ ls
pyproject.toml
vscode ➜ ~/tmp $ poetry add chainlit
Creating virtualenv tmp-M427n64X-py3.12 in /home/vscode/.cache/pypoetry/virtualenvs
Using version ^1.0.301 for chainlit

Updating dependencies
Resolving dependencies... (4.9s)

Package operations: 70 installs, 0 updates, 0 removals

  • Installing wrapt (1.16.0)
  • Installing zipp (3.17.0)
  • Installing deprecated (1.2.14)
  • Installing h11 (0.14.0)
  • Installing importlib-metadata (6.11.0)
  • Installing protobuf (4.25.3)
  • Installing backoff (2.2.1)
  • Installing certifi (2024.2.2)
  • Installing charset-normalizer (3.3.2)
  • Installing idna (3.6)
  • Installing opentelemetry-api (1.22.0)
  • Installing opentelemetry-proto (1.22.0)
  • Installing opentelemetry-semantic-conventions (0.43b0)
  • Installing sniffio (1.3.0)
  • Installing typing-extensions (4.9.0)
  • Installing urllib3 (2.2.1)
  • Installing wsproto (1.2.0)
  • Installing annotated-types (0.6.0)
  • Installing anyio (3.7.1)
  • Installing frozenlist (1.4.1)
  • Installing googleapis-common-protos (1.62.0)
  • Installing grpcio (1.60.1)
  • Installing multidict (6.0.5)
  • Installing opentelemetry-exporter-otlp-proto-common (1.22.0)
  • Installing opentelemetry-sdk (1.22.0)
  • Installing packaging (23.2)
  • Installing pydantic-core (2.16.2)
  • Installing requests (2.31.0)
  • Installing simple-websocket (1.0.0)
  • Installing aiosignal (1.3.1)
  • Installing attrs (23.2.0)
  • Installing bidict (0.23.1)
  • Installing httpcore (1.0.3)
  • Installing marshmallow (3.20.2)
  • Installing mypy-extensions (1.0.0)
  • Installing opentelemetry-exporter-otlp-proto-grpc (1.22.0)
  • Installing opentelemetry-exporter-otlp-proto-http (1.22.0)
  • Installing pydantic (2.6.1)
  • Installing python-engineio (4.9.0)
  • Installing setuptools (69.1.0)
  • Installing starlette (0.32.0.post1)
  • Installing yarl (1.9.4)
  • Installing aiohttp (3.9.3)
  • Installing click (8.1.7)
  • Installing fastapi (0.108.0)
  • Installing httpx (0.26.0)
  • Installing marshmallow-enum (1.5.1)
  • Installing opentelemetry-exporter-otlp (1.22.0)
  • Installing opentelemetry-instrumentation (0.43b0)
  • Installing python-socketio (5.11.1)
  • Installing typing-inspect (0.9.0)
  • Installing websockets (12.0)
  • Installing aiofiles (23.2.1)
  • Installing asyncer (0.0.2)
  • Installing dataclasses-json (0.5.9)
  • Installing fastapi-socketio (0.0.10)
  • Installing filetype (1.2.0)
  • Installing lazify (0.4.0)
  • Installing literalai (0.0.204)
  • Installing nest-asyncio (1.6.0)
  • Installing pyjwt (2.8.0)
  • Installing python-dotenv (1.0.1)
  • Installing python-graphql-client (0.4.3)
  • Installing python-multipart (0.0.6)
  • Installing syncer (2.0.3)
  • Installing tomli (2.0.1)
  • Installing uptrace (1.22.0)
  • Installing uvicorn (0.25.0)
  • Installing watchfiles (0.20.0)
  • Installing chainlit (1.0.301)

Writing lock file
vscode ➜ ~/tmp $ poetry run chainlit hello
Traceback (most recent call last):
  File "/home/vscode/.cache/pypoetry/virtualenvs/tmp-M427n64X-py3.12/bin/chainlit", line 5, in <module>
    from chainlit.cli import cli
  File "/home/vscode/.cache/pypoetry/virtualenvs/tmp-M427n64X-py3.12/lib/python3.12/site-packages/chainlit/__init__.py", line 22, in <module>
    import chainlit.input_widget as input_widget
  File "/home/vscode/.cache/pypoetry/virtualenvs/tmp-M427n64X-py3.12/lib/python3.12/site-packages/chainlit/input_widget.py", line 5, in <module>
    from chainlit.types import InputWidgetType
  File "/home/vscode/.cache/pypoetry/virtualenvs/tmp-M427n64X-py3.12/lib/python3.12/site-packages/chainlit/types.py", line 10, in <module>
    from literalai import ChatGeneration, CompletionGeneration
  File "/home/vscode/.cache/pypoetry/virtualenvs/tmp-M427n64X-py3.12/lib/python3.12/site-packages/literalai/__init__.py", line 1, in <module>
    from .client import LiteralClient
  File "/home/vscode/.cache/pypoetry/virtualenvs/tmp-M427n64X-py3.12/lib/python3.12/site-packages/literalai/client.py", line 4, in <module>
    from literalai.api import API
  File "/home/vscode/.cache/pypoetry/virtualenvs/tmp-M427n64X-py3.12/lib/python3.12/site-packages/literalai/api.py", line 11, in <module>
    from literalai.helper import ensure_values_serializable
  File "/home/vscode/.cache/pypoetry/virtualenvs/tmp-M427n64X-py3.12/lib/python3.12/site-packages/literalai/helper.py", line 1, in <module>
    from openai.types.chat import ChatCompletionMessage
ModuleNotFoundError: No module named 'openai'
vscode ➜ ~/tmp $ 
```

**Comment by nmstoker** [comment]
Thanks for digging into it @moritalous - I meant to comment earlier but was unable to.

@willydouhard your point was helpful to indicate the _intention_ regarding dependencies but the fact this happens immediately after a plain install suggests it would affect all users

**Comment by willydouhard** [comment]
I think I located the issue. You can try to upgrade the literalai package and this issue should be gone.

**Comment by nmstoker** [comment]
Excellent, that does the trick.

I ran:
`pip install literalai --upgrade --no-cache-dir --use-feature=truststore`
_(I expect the no cache dir wasn't necessary)_
and that bumped it up to 0.0.206.

Then chainlit 1.0.301 works fine, such as doing `chainlit init` which completes without any complaints.

Thank you for your efforts resolving this! 🙂

**Comment by willydouhard** [comment]
Awesome!
