### ISSUE TITLE
Error reloading module: 'opentelemetry.proto.collector'

### ISSUE THREAD

**Issue by a-stardust** [Chainlit/chainlit#784]
chainlit app runs properly when freshly run from terminal but fails to reload while saving the changes in prompt.py

error:

2024-03-03 00:17:03 - 1 change detected
2024-03-03 00:17:03 - File modified: prompt.py. Reloading app...
2024-03-03 00:17:05 - Error reloading module: 'opentelemetry.proto.collector'
2024-03-03 00:17:07 - You need to configure at least an on_chat_start or an on_message callback
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", 
line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\fastapi\applications.py", line 1054, 
in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\starlette\applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\starlette\middleware\exceptions.py", 
line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\starlette\_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\starlette\_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\starlette\routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\starlette\routing.py", line 459, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\engineio\async_drivers\asgi.py", line 58, in __call__
    await self.engineio_server.handle_request(scope, receive, send)
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\socketio\async_server.py", line 448, 
in handle_request
    return await self.eio.handle_request(*args, **kwargs)
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\engineio\async_server.py", line 286, 
in handle_request
    socket = self._get_socket(sid)
  File "C:\Users\Akshitha\Desktop\chainlitllm\.chainenv\lib\site-packages\engineio\base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'

**Comment by RomanKoshkin** [comment]
Same problem here. Posted (almost the same) [errors](https://github.com/Chainlit/chainlit/issues/745#issuecomment-2009465549).

**Comment by dokterbob** [comment]
What version (commit, release), what system, how can we replicate this?
