### ISSUE TITLE
Issue with `stringify_function_call()` When Invoking Multiple Parameter Sets

### ISSUE THREAD

**Issue by lianghsun** [Chainlit/chainlit#791]
I encountered an issue with the `stringify_function_call()` function. Everything works as expected when the function is invoked with a single set of parameters, as illustrated below:
```
{'name': 'some_function', 'arguments': '{"arg1: "value1"}'}
```
However, an error occurs when attempting to invoke `stringify_function_call()` with two sets of parameters simultaneously, as shown below:
```
{'name': 'some_function', 'arguments': '{"arg1: "value1"}{"arg1: "value2"}'}
```
The error message received is:
```
2024-03-06 12:14:44 - Extra data: line 1 column 69 (char 68)
Traceback (most recent call last):
  File "/home/myuser/.local/lib/python3.8/site-packages/chainlit/utils.py", line 39, in wrapper
    return await user_function(**params_values)
  File "app.py", line 336, in on_action
    await on_message(msg)
  File "app.py", line 310, in on_message
    tool_call_id = await call_gpt4(message_history)
  File "/home/myuser/.local/lib/python3.8/site-packages/chainlit/step.py", line 81, in async_wrapper
    result = await func(*args, **kwargs)
  File "app.py", line 147, in call_gpt4
    print(f"stringify_function_call: {stringify_function_call(function_output)}")
  File "/home/myuser/.local/lib/python3.8/site-packages/chainlit/playground/providers/openai.py", line 20, in stringify_function_call
    _function_call["arguments"] = json.loads(_function_call["arguments"])
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 69 (char 68)
```
I suggest that the `stringify_function_call()` function should be enhanced to accept multiple sets of parameters.

**Comment by willydouhard** [comment]
arguments should be a valid json I think? Why does it look like this?

**Comment by lianghsun** [comment]
Upon reviewing the code later, I discovered that I had made a mistake in one area, so there was no problem at all. This issue is closed.
