### ISSUE TITLE
Error since 1.0.500 upgrade: OSError: [Errno 30] Read-only file system: '/app/.files'"

### ISSUE THREAD

**Issue by MarkEdmondson1234** [Chainlit/chainlit#867]
**Describe the bug**
Now deploying to Cloud Run I get this error, with the same code.

Has the file location changed?  This directory is read-only on Cloud Run - is it possible to configure it to write somewhere else?

```
Traceback (most recent call last):
  File "/usr/local/bin/chainlit", line 5, in <module>
    from chainlit.cli import cli
  File "/usr/local/lib/python3.10/site-packages/chainlit/__init__.py", line 24, in <module>
    from chainlit.action import Action
  File "/usr/local/lib/python3.10/site-packages/chainlit/action.py", line 5, in <module>
    from chainlit.telemetry import trace_event
  File "/usr/local/lib/python3.10/site-packages/chainlit/telemetry.py", line 12, in <module>
    from chainlit.config import config
  File "/usr/local/lib/python3.10/site-packages/chainlit/config.py", line 34, in <module>
    FILES_DIRECTORY.mkdir(exist_ok=True)
  File "/usr/local/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [Errno 30] Read-only file system: '/app/.files'"
```

**Comment by MarkEdmondson1234** [comment]
I found the issue - I was linking a Cloud Storage bucket to Cloud Run for my config, and it made the folder read only.  Coincidence it happened after release :) thanks for reply
