### ISSUE TITLE
Unable to fetch History from literal.ai

### ISSUE THREAD

**Issue by rajeshshanmugam-s** [Chainlit/chainlit#881]
**Describe the bug**
While using literal API key it is throwing the below error, Chat history is not loaded from the literal.ai

```
Exception: [{'message': 'Unknown type "FeedbackPayloadInput". Did you mean "ThreadPayloadInput", "GenerationPayloadInput", or "ScorePayloadInput"?', 'locations': [{'line': 14, 'column': 22}]}, {'message': 'Unknown argument "feedback" on field "Mutation.ingestStep".', 'locations': [{'line': 31, 'column': 9}]}]
```

**To Reproduce**

Run the below snippet with `LITERAL_API_KEY` in .env
```python 
import chainlit as cl

@cl.on_message
async def on_message(message: cl.Message):
    msg = cl.Message(content="Working")
    await msg.send()
````

**Expected behavior**
Load the chat history from Literal.ai

**Comment by KIBASSA** [comment]
Hi,
Has this bug been fixed ? 
Or do I need to use an earlier version of chainlit to avoid it?

**Comment by constantinidan** [comment]
Hi, can you please upgrade chainlit? pip install -U chainlit
it should fix the bug
thanks!

**Comment by rajeshshanmugam-s** [comment]
After updating it throws the below error 

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Documents\usecases\Langchain Chtbot\env_final\Scripts\chainlit.exe\__main__.py", line 4, in <module>
  File "C:\Users\Documents\usecases\Langchain Chtbot\env_final\Lib\site-packages\chainlit\__init__.py", line 24, in <module>
    from chainlit.action import Action
  File "C:\Users\Documents\usecases\Langchain Chtbot\env_final\Lib\site-packages\chainlit\action.py", line 5, in <module>
    from chainlit.telemetry import trace_event
  File "C:\Users\Documents\usecases\Langchain Chtbot\env_final\Lib\site-packages\chainlit\telemetry.py", line 12, in <module>
    from chainlit.config import config
  File "C:\Users\Documents\usecases\Langchain Chtbot\env_final\Lib\site-packages\chainlit\config.py", line 469, in <module>
    config = load_config()
             ^^^^^^^^^^^^^
  File "C:\Users\Documents\usecases\Langchain Chtbot\env_final\Lib\site-packages\chainlit\config.py", line 438, in load_config
    settings = load_settings()
               ^^^^^^^^^^^^^^^
  File "C:\Users\Documents\usecases\Langchain Chtbot\env_final\Lib\site-packages\chainlit\config.py", line 408, in load_settings
    features_settings = FeaturesSettings(**features_settings)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Documents\usecases\Langchain Chtbot\env_final\Lib\site-packages\pydantic\_internal\_dataclasses.py", line 135, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
pydantic_core._pydantic_core.ValidationError: 1 validation error for FeaturesSettings
multi_modal
  Input should be a dictionary or an instance of MultiModalFeature [type=dataclass_type, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.6/v/dataclass_type
```
