### ISSUE TITLE
Issue trying to run chainlit on Ubuntu 22.04

### ISSUE THREAD

**Issue by chibexme** [Chainlit/chainlit#904]
I tried running `chainlit hello` and my app too that works well on Windows 11 `chainlit run app.py -w -h` but get below error:

Traceback (most recent call last):
  File "/usr/local/bin/chainlit", line 5, in <module>
    from chainlit.cli import cli
  File "/usr/local/lib/python3.8/dist-packages/chainlit/__init__.py", line 24, in <module>
    from chainlit.action import Action
  File "/usr/local/lib/python3.8/dist-packages/chainlit/action.py", line 5, in <module>
    from chainlit.telemetry import trace_event
  File "/usr/local/lib/python3.8/dist-packages/chainlit/telemetry.py", line 12, in <module>
    from chainlit.config import config
  File "/usr/local/lib/python3.8/dist-packages/chainlit/config.py", line 469, in <module>
    config = load_config()
  File "/usr/local/lib/python3.8/dist-packages/chainlit/config.py", line 438, in load_config
    settings = load_settings()
  File "/usr/local/lib/python3.8/dist-packages/chainlit/config.py", line 408, in load_settings
    features_settings = FeaturesSettings(**features_settings)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/_internal/_dataclasses.py", line 140, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
pydantic_core._pydantic_core.ValidationError: 1 validation error for FeaturesSettings
multi_modal
  Input should be a dictionary or an instance of MultiModalFeature [type=dataclass_type, input_value=False, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.7/v/dataclass_type

chainlit version is chainlit-1.0.502

The error is about pydantic validator.

**Comment by s0l4r** [comment]
Exactly same issue with 
```
chainlit                                 1.0.502         Build Conversational AI.
pydantic                                 2.7.0           Data validation using Python type hints
pydantic-core                            2.18.1          Core functionality for Pydantic validation and serialization
```

Python: 3.12.1

**Comment by chibexme** [comment]
> Exactly same issue with:
> 
> ```
> chainlit                                 1.0.502         Build Conversational AI.
> pydantic                                 2.7.0           Data validation using Python type hints
> pydantic-core                            2.18.1          Core functionality for Pydantic validation and serialization
> ```
> 
> Python: 3.12.1
> 
> Working with pydantic 2.7.0 and:
> 
> ```
> chainlit                                 1.0.401         Build Conversational AI.
> ```

This version worked. Thanks.

**Comment by dsolito** [comment]
Same problem.
rollback to 1.0.401 works
