### ISSUE TITLE
Getting the Config file outdated error while running the app

### ISSUE THREAD

**Issue by adithyaboyapati** [Chainlit/chainlit#99]
I was getting the following error while running the chainlit app:

Traceback (most recent call last):
  File "/Users/user1/Desktop/Machine_Learning/Chainlit-Zomato-GPT/env/bin/chainlit", line 5, in <module>
    from chainlit.cli import cli
  File "/Users/user1/Desktop/Machine_Learning/Chainlit-Zomato-GPT/env/lib/python3.9/site-packages/chainlit/__init__.py", line 8, in <module>
    from chainlit.config import config
  File "/Users/user1Desktop/Machine_Learning/Chainlit-Zomato-GPT/env/lib/python3.9/site-packages/chainlit/config.py", line 251, in <module>
    config = load_config()
  File "/Users/user1/Desktop/Machine_Learning/Chainlit-Zomato-GPT/env/lib/python3.9/site-packages/chainlit/config.py", line 239, in load_config
    settings = load_settings()
  File "/Users/user1/Desktop/Machine_Learning/Chainlit-Zomato-GPT/env/lib/python3.9/site-packages/chainlit/config.py", line 201, in load_settings
raise ValueError(
ValueError: Your config file is outdated. Please delete it and restart the app to regenerate it.

**Comment by willydouhard** [comment]
Yes, you just have to delete the  `.chainlit/config.toml` file once and restart your app!

**Comment by btconway** [comment]
I'm also having this issue but can't even fin the .chainlit/config.toml file. I've tried unintsalling and reinstalling and keep getting this error even if I've done a fresh install and am typing `chainlit hello` in terminal

**Comment by manishTerminal** [comment]
where is config file. tell me the location its not showing

**Comment by willydouhard** [comment]
the config file is an folder named .chainlit. This folder is created at the same level you ran your chainlit command.
